---
title: "P8106 Homework 1"
author: "Pengyuan Su (ps3195)"
date: "2/9/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(pls)

knitr::opts_chunk$set(
  fig.height = 6,
  message = F,
  echo = T,
  warning = F,
  cache = T
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
# Import data

sol_train = 
  read_csv("./data/solubility_train.csv") %>% 
  janitor::clean_names()

sol_test = 
  read_csv("./data/solubility_test.csv") %>% 
  janitor::clean_names()

x_train = model.matrix(solubility ~., sol_train)[, -1]
y_train = sol_train$solubility

x_test = model.matrix(solubility ~., sol_test)[,-1]
y_test = sol_test$solubility

ctr <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
```


# Question 1

```{r lm}
set.seed(5)
fit.lm = 
  train(
    solubility ~.,
    data = sol_train,
    method = "lm",
    trControl = ctr
  )

RMSE(predict(fit.lm, newdata = sol_test), sol_test$solubility)^2
```

# Question 2

```{r ridge}
set.seed(5)

fit.ridge = 
  train(
    solubility ~.,
    data = sol_train,
    method = "glmnet",
    tuneGrid = 
      expand.grid(
        alpha = 0, 
        lambda = exp(seq(from = -1, to = -5, length = 1000))
        ),
    trControl = ctr,
    preProcess = c("center", "scale")
  )

plot(fit.ridge, xTrans = log)

fit.ridge$bestTune

RMSE(predict(fit.ridge, s = "lamda.min", newdata = sol_test), sol_test$solubility)^2
```

# Question 3

```{r lasso}
set.seed(5)
fit.lasso = 
  train(
    solubility ~.,
    data = sol_train,
    method = "glmnet",
    tuneGrid = 
      expand.grid(
        alpha = 1,
        lambda = exp(seq(from = -1, to = -8, length = 1000))
      ),
    trControl = ctr,
    preProcess = c("center", "scale")
  )

plot(fit.lasso, xTrans = log)

fit.lasso$bestTune

RMSE(predict(fit.lasso, s = "lambda.min", newdata = sol_test), sol_test$solubility)^2


sum(coef(fit.lasso$finalModel, s = fit.lasso$bestTune$lambda)!=0)
```


# Question 4

```{r pcr}
set.seed(5)
fit.pcr =
  train(
    solubility~.,
    data = sol_train,
    method = "pcr",
    tuneGrid = 
      expand.grid(ncomp = seq(1,ncol(sol_train))),
    preProcess = c("center","scale"),
    trControl = ctr
  )

fit.pcr$bestTune #Find the best M

validationplot(fit.pcr$finalModel, val.type="MSEP", legendpos = "topright")

RMSE(predict(fit.pcr, x_test), y_test)^2 # Calculate MSE
mean((predict(fit.pcr, x_test) - y_test)^2) # Check
```

# Question 5

```{r}
resample = 
  resamples(list(
    lm = fit.lm,
    ridge = fit.ridge,
    lasso = fit.lasso,
    pcr = fit.pcr
  ))

summary(resample)

bwplot(resample, metric = "RMSE")
```

From numeric result and boxplot, Lasso model has the smallest RMSE, MAE, and the highest R^2, hence we will choose it for predicting solubility.
